### ISSUE TITLE
Plugin Compiling

### ISSUE THREAD

**Issue by Resoluciones** [NerdNu/Zombageddon#1]
Hi!  Thanks for this wonderful plugin!

Can you tell me how to compile it?  I've downloaded the mirrormirror, but where do I have to paste it?  Currently I get error when trying to compile it with /mvn clean package.

Sorry for my little knowledge!

Thanks!!!!

**Comment by redwallhp** [comment]
You're on the right track. For Maven to compile Zombageddon, you first have to use Maven to compile MirrorMirror. If you download the MirrorMirror source from its repository and run `mvn install`, it will compile and install MM into Maven's dependency store. Now you can compile Zombageddon with `mvn clean package` and it will be able to find MM.

**Comment by redwallhp** [comment]
http://rdwl.xyz/blog/how-to-compile-spigot-plugins/
